services:
  - type: web
    name: churnguard-api
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: HF_REPO_ID
        value: shraddharaom/churnguard-models
